[package]
name = "ggorgxyz"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
wasm-logger = "0.2.0"
yew = { version = "0.21", features = ["csr"] }
yew-autoprops = "0.4.1"
